Pur_Beurre/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from catalog import views as cata_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('favorite/', user_views.favorite, name='favorite'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"

urlpatterns = [
    path('', views.index, name='index'),
    path('mentions-legales/', views.legal, name='legal'),
    path('search/', views.search, name='search'),
    path('substitute/<str:product_id>/', views.product_detail, name='product_detail'),
    path('add_favorite/<str:product_id>/', views.add_favorite, name='add_favorite'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
	name = models.CharField(max_length=100)


class  Product(models.Model):
	name = models.CharField(max_length=200, unique=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="product")
	brand = models.CharField(max_length=200)
	nutrition_grade = models.CharField(max_length=1)
	picture = models.URLField()
	nutrition_image = models.URLField()
	url = models.URLField()


class UserFavorite(models.Model):
	user_name = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

catalog/views.py
import requests
import json

from django.shortcuts import render, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

from .models import Product, Category, UserFavorite
# Create your views here.


def index(request):
    return render(request, 'catalog/index.html')

def legal(request):
    return render(request, 'catalog/mlegal.html')



def autocomplete(request):

	if request.is_ajax():
		query = request.GET.get('term', '')
		products = Product.objects.filter(name__icontains=query).order_by("-nutrition_grade")[:10]
		results = []
		for p in products:
			product_dict = {}
			product_dict = p.name
			results.append(product_dict)
		data = json.dumps(results)
	else:
		data = 'fail'
	return HttpResponse(data, 'application/json')



def search(request):

    query = request.GET.get('query')

    try:
        product = Product.objects.filter(name=query).first()
        substitutes = Product.objects.filter(category=product.category, nutrition_grade__lt=product.nutrition_grade).order_by("nutrition_grade")

        paginator = Paginator(substitutes, 6)
        page = request.GET.get('page')
        alt_products = paginator.get_page(page)

        context = {
        	'alt_products': alt_products,
        	'paginate': True,
            'title': query,
            'image': product.picture,
            'query': query,
        }

    except AttributeError:
        messages.warning(request, "Ce produit n'existe pas. Vérifiez l'orthographe de la recherche")
        return redirect('catalog:index')

    return render(request, 'catalog/search.html', context)



def product_detail(request, product_id):
    
    product = Product.objects.get(id=product_id)

    context = {
        'name': product.name,
        'title': 'Informations nutritionnelles',
        'product': product,
        'nutrition_image': product.nutrition_image,
    }

    return render(request, 'catalog/product_detail.html', context)



@login_required
def add_favorite(request, product_id):
    try:
        UserFavorite.objects.get(user_name_id=request.user.id, product_id=(product_id))
        messages.warning(request, 'Ce produit est déjà dans vos favoris.')
        return redirect(request.META.get('HTTP_REFERER'))
    except ObjectDoesNotExist:
        UserFavorite.objects.create(user_name_id=request.user.id, product_id=(product_id))
        messages.success(request, 'Le produit a bien été enregistré.')
        return redirect(request.META.get('HTTP_REFERER'))

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegisterForm

from catalog.models import UserFavorite, Product

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Votre compte a bien été crée')
            return redirect('catalog:index')
    else:
        form = UserRegisterForm()
        
    return render(request, 'users/register.html', {'form': form})


 
@login_required
def profile(request):
    return render(request, 'users/profile.html')


@login_required
def favorite(request):

    user = request.user
    fav = Product.objects.filter(userfavorite__user_name=user.id)
    if fav:
        product = Product.objects.filter(pk__in=fav)
    else:
        product = []

    return render(request, 'users/favorite.html', {'favorite': product})

catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" href="{% static 'catalog/img/pur-beurre-small.png' %}" />

    <title>Pur Beurre</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'catalog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'catalog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'catalog/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'catalog/css/creative.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <img id="logo" src="{% static 'catalog/img/pur-beurre.png' %}" title="Pur Beurre" alt="Pur Beurre" />
        <a class="navbar-brand js-scroll-trigger" href="{% url 'catalog:index' %}">Pur Beurre</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

            <li>
              <form id="search-nav"  action="{% url 'catalog:search' %}" method="get" accept-charset="utf-8">
                  <input type="text" name="query" id ="querynav" placeholder="Chercher un produit" required>
              </form>
            </li>

            {% if user.is_authenticated %}

            <li class="nav-item icon">
              <a href="{% url 'profile' %}"> <i class="fas fa-user fa-2x" data-toggle="tooltip" title="Mon Profile" ></i></a>
            </li>
            <li class="nav-item icon">
              <a href="{% url 'favorite' %}"> <img id="carot" src="{% static 'catalog/img/carot.png' %}" title="Mes produits"/> </a>
            </li>
            <li class="nav-item icon">
              <a href="{% url 'logout' %}"> <i class="fas fa-sign-out-alt fa-2x" data-toggle="tooltip" title="Déconnexion" ></i></a>
            </li>

            {% else %}
            <li class="nav-item icon">
              <a href="{% url 'login' %}"> <i class="fas fa-sign-in-alt fa-2x" data-toggle="tooltip" title="Se Connecter" ></i></a>
            </li>
            <li class="nav-item icon">
              <a href="{% url 'register' %}"> <i class="fas fa-user-plus fa-2x" data-toggle="tooltip" title="S'inscrire" ></i></a>
            </li>
            {% endif %}            
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <footer>
          <div class="container">
            <div class="row">
              <div class="col-lg-8 mx-auto text-center">
                <a href="{% url 'catalog:legal' %}">Mentions légales</a>
                <a href="/#contact">Contact</a>
              </div>
            </div>
          </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'catalog/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'catalog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'catalog/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'catalog/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'catalog/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'catalog/js/creative.min.js' %}"></script>
    <script src="{% static 'catalog/js/custom.js' %}"></script>

    <!-- jQuery !-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
    <!-- jQuery UI !-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

  </body>

</html>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load static %}


<header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Du gras oui, mais de qualité !</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">Trouvez un produit de subsitution pour ceux que vous consommez tous les jours</p>
            
            <form id="search"  action="{% url 'catalog:search' %}" method="get" accept-charset="utf-8">
                <input type="text" name="query" id ="query" placeholder="Entrez le produit que vous voulez remplacer" required>
                <button type="submit" class="btn btn-primary btn-search">Chercher</button>
            </form>

            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}

          </div>
        </div>
      </div>
</header>
<section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Colette et Rémy</h2>
            <hr class="my-4">
            <p class="text-muted mb-0">Nous sommes une jeune startup fondée par Remy et Colette Tatou, deux restaurateurs de renom. Notre restaurant, situé à Montmartre (Paris), compte une cinquantaine de couverts et ne désemplit pas. Notre spécialité, la ratatouille, nous attire une clientèle internationale charmée par les délices de ce plat typique. </p>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-9 text-center">
            <div class="service-box mt-5 mx-auto">
              <img src="{% static 'catalog/img/colette.jpg' %}" title="Colette" alt="Colette" />
              <p class="text-muted mb-0 mt-2">Colette</p>
            </div>
          </div>
          <div class="col-lg-6 col-md-9 text-center">
            <div class="service-box mt-5 mx-auto">
              <img src="{% static 'catalog/img/remy.jpg' %}" title="Rémy" alt="Rémy" />
              <p class="text-muted mb-0 mt-2">Rémy</p>
            </div>
          </div>
    </section>


    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading">Contactez-nous !</h2>
            <hr class="my-4">
            <p class="mb-5">Vous avez trouvé une erreur sur le site ? Il y a  un problème avec un produit ? N'hésitez pas à nous contacter</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fas fa-phone fa-3x mb-3 sr-contact-1"></i>
            <p>12-34-56-67-89</p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fas fa-envelope fa-3x mb-3 sr-contact-2"></i>
            <p>
              <a href="mailto:your-email@your-domain.com">contact@purbeurre.com</a>
            </p>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

catalog/templates/catalog/mlegal.html
{% extends 'catalog/base.html' %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Mentions légales</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section id="legal">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        	<h2>Responsables</h2>
        	<hr>
        	<p>Colette et Rémy.</p>
        	<p>Tél. : 12-34-56-67-89</p>
        	<p>Mail : contact@purbeurre.com</p>
        	<br>
        	<h2>Resources</h2>
        	<hr>
        	<p>Le site est heberge par <a href="https://www.heroku.com/">Heroku</a> dans sa version gratuite.</p>
      <p>Les données sont issues de la base <a href="https://openfoodfacts.org">OpenFoodFacts</a></p>  
			<p><em>La photo de la banière en haut de page est de : </em><a href="https://unsplash.com/photos/eqsEZNCm4-c"> Olenka Kotyk</a></p>
      <p><em>L'icone carotte est de : </em> <a href="https://thenounproject.com/FabienJ/"> Fabien Jouin </a></p>
			<p><em>Thème utilisé : </em><a href="https://startbootstrap.com/template-overviews/creative/">Startbootstrap-creative</a></p>
			<p><em>Conception du site</em> : Elia Benfatto. <br/></p>
       <p>Le présent site est le travail d'étude issu du 8ème projet du <a href="https://openclassrooms.com/fr/paths/68-developpeur-dapplication-python" title="Open Classrooms - Développeur d'application Python">pacours développeur d'application Python</a> proposé par <a href="https://openclassrooms.com" title="Site d'OpenClassrooms">OpenClassrooms</a>.</p>
      </div>  
   </div>
  </div>
</section>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="smallheader text-center text-white d-flex" style="background-image: url({{ product.picture }}) !important;">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>{{ product.name }}</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section id="detail">
<div class="container my-auto">
        <div class="row">
            <div id="detail" class="col-lg-12 text-center">

                <h2 class="section-heading">{{ title }}</h2>
                <hr class="my-4">
                <br>
                
                <img class="product-detail-img" src="https://static.openfoodfacts.org/images/misc/nutriscore-{{ product.nutrition_grade }}.svg" alt="nutrition score {{ product.nutrition_grade }}" title="Nutri-score {{ product.nutrition_grade }}" />
                <img class="product-detail-img" src="{{ product.nutrition_image}}" alt="nutrition 100g" title="Nutrition 100g" />
                <br>

                <a href="{{ product.url}}" class="btn btn-primary btn-xl mt-50" target="_blank">Voir la fiche Open Food Facts</a>
            </div>       
        </div>
</div>
</section>

{% endblock content %}

catalog/templates/catalog/search.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="smallheader text-center text-white d-flex" style="background-image: url({{ image }}) !important;">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>{{ title }}</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<div class="container my-auto">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
</div>
<section>
	<div class="container">
		<div class="col-md-18 text-center">    
		        <h2 class="section-heading">Vous pouvez remplacer cet aliment par :</h2>
		        <hr>
				{% for new_product in alt_products %}
					<div class="card product-card">
						<div class="product-card-badge">
                            <span class="product-nutrigrade badge badge-{{ new_product.nutrition_grade }}">{{ new_product.nutrition_grade }}</span>
                        </div>
						<div class="product-card-img" style="background-image: url({{ new_product.picture }})"></div>         
				            <div class="card-body">
				            <h4 class="card-title product-card-title">{{ new_product.name }}</h4>
							
							<a href="{% url 'catalog:product_detail' product_id=new_product.id %}"> détails</a>

							{% if user.is_authenticated %}
							<div class="save-result" id="{{new_product.id}}"></div>
							<form method="post" action="{% url 'catalog:add_favorite' product_id=new_product.id%}">
							    {% csrf_token %}
							    <input class="btn btn-primary btn-xl mt-50" type="submit" value="Sauvegarder" id="{{new_product.id}}">
							</form>
							{% endif %}
						</div>
					</div>
				{% endfor %}

				{% if paginate %}
				{% url 'catalog:search' as alt_url %}

				  {% if alt_products.has_previous %}
				    <a class="btn btn-outline-dark mb-4" href="?query={{query}}&page=1">Début</a>
				    <a class="btn btn-outline-dark mb-4" href="?query={{query}}&page={{ alt_products.previous_page_number }}">Précedent</a>
				  {% endif %}

				  {% for num in alt_products.paginator.page_range %}
				    {% if alt_products.number == num %}
				      <a class="btn btn-dark mb-4" href="?query={{query}}&page={{ num }}">{{ num }}</a>
				    {% elif num > alt_products.number|add:'-3' and num < alt_products.number|add:'3' %}
				      <a class="btn btn-outline-dark mb-4" href="?query={{query}}&page={{ num }}">{{ num }}</a>
				    {% endif %}
				  {% endfor %}

				  {% if alt_products.has_next %}
				    <a class="btn btn-outline-dark mb-4" href="?query={{query}}&page={{ alt_products.next_page_number }}">Suivant</a>
				    <a class="btn btn-outline-dark mb-4" href="?query={{query}}&page={{ alt_products.paginator.num_pages }}">Fin</a>
				  {% endif %}

				{% endif %}

				<div class="clearfix"></div>                
		</div>
	</div>	
</section>
{% endblock content %}

users/templates/users/favorite.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Mes produits</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section id="favorite">
	<div class="container text-center my-auto">
		<div>
		    <h3>Liste produits favoris</h3>
		    <hr> 
		        {% for product in favorite %}
		                <p><a href="{{ product.url }}">{{product.name}} - ({{ product.nutrition_grade }})</a></p>
		        {% endfor %}             
		</div>
	</div>
</section>
{% endblock content %}     

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Connexion</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section id="connexion" class="text-center d-flex">
    <div class="container my-auto">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h3 class="border-bottom mb-4">Connectez-vous à votre compte Pur Beurre!</h3>

            <div class="fieldWrapper my-label">
                <label for="{{ form.username.id_for_label }}">Nom d'utilisateur</label>
                {{ form.username }}
            </div>

            <div class="fieldWrapper my-label">
                <label for="{{ form.password.id_for_label }}">Mot de passe</label>
                {{ form.password }}
            </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary btn-xl mt-50" type="submit">Connexion</button>
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Mot de passe oublié ?</a>
                </small>
            </div>
        </form>
        <div>           
                Besoin d'un compte? <a href="{% url 'register' %}">S'inscrire</a>
        </div>
    </div>
</section>
{% endblock content %}

users/templates/users/logout.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="masthead text-center text-white d-flex">
	<div class="container my-auto">
	    <h2>Vous êtes déconnecté</h2>
	    <div>
	        <small>
	            vous avez un compte ?<a href="{% url 'login' %}">connectez-vous</a>
	        </small>
	    </div>
	</div>
</header>
{% endblock content %}

users/templates/users/password_reset.html
{% extends 'catalog/base.html' %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Nouveau mot de passe</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section id="nouveaumdp" class="text-center d-flex">
    <div class="container my-auto">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h3 class="border-bottom mb-4">réinitialiser votre mot de passe!</h3>

            <div class="fieldWrapper my-label">
                <label for="{{ form.email.id_for_label }}">Adresse email</label>
                {{ form.email }}
            </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary btn-xl mt-50" type="submit">Request reset</button>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="masthead text-center text-white d-flex">
	<div class="container my-auto">
	    <h2>Votre mot de passe a bien été modifié</h2>
	</div>
</header>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'catalog/base.html' %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Nouveau mot de passe</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section id="nouveaumdp" class="text-center d-flex">
    <div class="container my-auto">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h3 class="border-bottom mb-4">réinitialiser votre mot de passe!</h3>
            
            <div class="fieldWrapper my-label">
                <label for="id_new_password1">Mot de passe</label>
                {{ form.new_password1 }}
            </div>

            <div class="fieldWrapper my-label">
                <label for="id_new_password2">Confirmation mdp</label>
                {{ form.new_password2 }}
            </div>

            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary btn-xl mt-50" type="submit">Changer mon mot de passe</button>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="masthead text-center text-white d-flex">
	<div class="container my-auto">
	    <h2>Vous allez recevoir un email avec les instructions pour récuperer le mot de passe</h2>
	</div>
</header>
{% endblock content %}

users/templates/users/profile.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>{{ user.username }}</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section id="account">
	<div class="container text-center my-auto">
        <div>
            <h3>Informations sur mon compte</h3>
            <hr>
            <p>Email: {{ user.email }}</p>
        </div>
        <br>  	
    </div>
</section>
{% endblock content %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Inscription</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section class="text-center d-flex">
    <div class="container my-auto">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h3 class="border-bottom mb-4">Créez votre compte Pur Beurre!</h3>
            </fieldset>
            
            <div class="fieldWrapper my-label">
                <label for="{{ form.username.id_for_label }}">Nom d'utilisateur</label>
                {{ form.username }}
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <p class="errorform">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="fieldWrapper my-label">
                <label for="{{ form.email.id_for_label }}">Adresse email</label>
                {{ form.email }}
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <p class="errorform">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="fieldWrapper my-label">
                <label for="{{ form.password.id_for_label }}">Mot de passe</label>
                {{ form.password1 }}
                {% if form.password1.errors %}
                    {% for error in form.password1.errors %}
                        <p class="errorform">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="fieldWrapper my-label">
                <label for="{{ form.password.id_for_label }}">Confirmation mdp</label>
                {{ form.password2 }}
                {% if form.password2.errors %}
                    {% for error in form.password2.errors %}
                        <p class="errorform">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            
            <br>
            
            <div class="form-group">
                <button class="btn btn-primary btn-xl mt-50" type="submit">S'inscrire</button>
            </div>
        </form>
        <div>
                Vous avez déjà un compte? <a href="{% url 'login' %}">Connexion</a>
        </div>
    </div>
</section>
{% endblock content %}